- hosts: demo
  user: ansible
  connection: ssh
  become: yes
  vars:
      pkgname: putty
  tasks:
                - name: install putty on ubuntu 20
                  action: apt name="{{pkgname}}" state=present
  
